# Generated by Django 5.1.3 on 2024-11-26 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('adresse', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='candidat',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='competences',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recruteur',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.entreprise'),
        ),
        migrations.CreateModel(
            name='OffreEmploie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date_poste', models.DateField()),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adresse', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('recruteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recruteur')),
            ],
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_candidature', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('en_attente', 'en_attente'), ('vue', 'vue'), ('accepter', 'accepter'), ('rejeter', 'rejeter')], default='en_attente', max_length=20)),
                ('lettre_motivation', models.FileField(blank=True, null=True, upload_to='lettre_motivation/')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.candidat')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.offreemploie')),
            ],
        ),
    ]
