# Generated by Django 5.1.3 on 2024-11-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_entreprise_candidat_linkedin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='user',
        ),
        migrations.AlterField(
            model_name='candidat',
            name='competences',
            field=models.TextField(blank=True, null=True),
        ),
    ]
