# Generated by Django 5.1.3 on 2024-11-26 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_recruteur_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='lettre_motivation',
            field=models.FileField(blank=True, null=True, upload_to='lettre_motivation/'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='candidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='candidatures', to='api.candidat'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='offre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='api.offreemploie'),
        ),
    ]
