# Generated by Django 5.1.3 on 2024-11-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_candidat_user_alter_recruteur_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('recruteur', 'Recruteur'), ('candidat', 'Candidat')], default='candidat', max_length=20),
        ),
    ]
