# Generated by Django 5.1.3 on 2024-11-28 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_recruteur_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('addresse', models.CharField(max_length=200)),
                ('town', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_poste', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('addresse', models.CharField(max_length=200)),
                ('town', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='candidature',
            name='candidat',
        ),
        migrations.RemoveField(
            model_name='candidature',
            name='offre',
        ),
        migrations.RemoveField(
            model_name='recruteur',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='offreemploie',
            name='recruteur',
        ),
        migrations.RemoveField(
            model_name='recruteur',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('recruiter', 'Recruiter'), ('candidate', 'Candidate')], default='candidate', max_length=20),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('experience', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('cover_lettre', models.FileField(blank=True, null=True, upload_to='cover_lettre/')),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('seen', 'seen'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=20)),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='cover_letters/')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='applications', to='api.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.joboffer')),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='joboffer',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recruiter'),
        ),
        migrations.DeleteModel(
            name='Candidat',
        ),
        migrations.DeleteModel(
            name='Candidature',
        ),
        migrations.DeleteModel(
            name='Entreprise',
        ),
        migrations.DeleteModel(
            name='OffreEmploie',
        ),
        migrations.DeleteModel(
            name='Recruteur',
        ),
    ]
